#version: '3.8'

services:
  luma-frontend-svelte:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    environment:
      - PORT=${FRONTEND_PORT}
      - VITE_API_URL=${FRONTEND_API_URL}
    networks:
      - luma-network
    restart: unless-stopped

networks:
  luma-network:
    name: ${DOCKER_NETWORK_NAME}
    external: true
